- nemo-image-converter/data/nemo-image-rotate.ui
taken from this commit:
https://git.gnome.org/browse/nautilus-image-converter/commit/?id=23441ed6d74b4eba68333c802890cb396721a6d6
> [nemo-image-converter] fix rotate dialog - it didn't show because of the obsolete property

- nemo-terminal/src/nemo_terminal.py
Apparently wchan handling for bash changed in recent linux kernels (>3.19 as far as I know). Added 2 elif for handling current wchan states : wait_woken and do_wait. I tried to get the schedule and n_tty_read states but could not.
The relevancy of the rest of _shell_is_busy thus needs to be further tested.
Works on my machine, confirmed by skualos in linuxmint#113
> temp fix for the no auto cd problem in recent linux kernels

- nemo-terminal/src/org.nemo.extensions.nemo-terminal.gschema.xml
As per the key's description, leaving key blank will result in nemo-terminal using user-shell, rather than defaulting to bash. Other function, such as  the change-directory-command, remain in tact.
resolves #141
> Changed default shell from bash, to user shell

- nemo-share/debian/control
- nemo-share/src/nemo-share.c
Since we're using Debian packaging, we can assume that dependencies
are already installed.
This also removes the dependencies on cinnamon-session and apturl
(the latter so that the package is installable on stock Debian).
Fixes #146.
> nemo-share: remove samba auto-installation code

- nemo-seahorse/configure.ac
As GNOME does the same with its nautilus-seahorse:
https://git.gnome.org/browse/seahorse-nautilus/commit/?id=0fad0fcf8adca04f9b0a5a8832a268c835fcd9bd
Fixes linuxmint/nemo-extensions#159
> seahorse: Allow building with gnupg 2.1

- nemo-terminal/src/org.nemo.extensions.nemo-terminal.gschema.xml
By adding '&& tput cuu1 && tput el' to terminal-change-directory-command changing directories becomes much cleaner. tput is a standard unix system command, so it should be found on most (if not all) distributions.
> Nemo Terminal: Clear 'cd' line after changing directory

- nemo-preview/src/js/viewers/audio.js
Based on https://git.gnome.org/browse/sushi/patch/src/js?id=1c0977f28177109e738ff81a4ac4dcc99c064c76
From 1c0977f28177109e738ff81a4ac4dcc99c064c76 Mon Sep 17 00:00:00 2001
From: Cosimo Cecchi <cosimoc@gnome.org>
Date: Sat, 14 Nov 2015 11:36:10 -0800
Subject: audio: fix missing import
This was causing album art not to display.
> audio: fix missing import

- nemo-preview/data/style/gtk-style.css
Corrects invalid values for the `font` attribute in `nemo-preview/data/style/gtk-style.css`
> Fixes Issue #189: Invalid CSS values in nemo-preview

- nemo-emblems/nemo-extension/nemo-emblems.py
Issue present on mint-18.1
```
caroline@caroline-ThinkPad-T410 ~ $ /usr/lib/nemo/nemo-extensions-list
Initializing nemo-image-converter extension
NEMO_EXTENSION:::NemoImageConverter:::Nemo Image Converter:::Allows image resizing and rotation from the context menu
NEMO_EXTENSION:::NemoShare:::Nemo Share:::Allows you to quickly share a folder from the context menu
NEMO_EXTENSION:::EmblemPropertyPage+NemoPythonTraceback (most recent call last):
File "/usr/share/nemo-python/extensions/nemo-emblems.py", line 138, in get_name_and_desc
return [_("Nemo Emblems:::Change a folder or file emblem")]
NameError: global name '_' is not defined
Segmentation fault
```
> nemo-emblems: Fix error

- nemo-compare/src/nemo-compare.py
```
File "/usr/share/nemo-python/extensions/nemo-compare.py", line 166, in get_name_and_desc
return [_("Nemo Compare:::Allows file comparison from the context menu")]
NameError: global name '_' is not defined
```
> nemo-compare: Fix error

- nemo-fileroller/configure.ac
nemo-fileroller fails to cross build from source, because it uses the
build architecture pkg-config. Its configure.ac uses handcrafted rules
for discovering pkg-config and fails to consider ac_tool_prefix. By
moving to standard macros, this problem can be avoided and thus
nemo-fileroller can be cross built.
Debian-Bug: https://bugs.debian.org/843800
> Use a triplet-prefixed pkg-config for cross compilation

- nemo-emblems/nemo-extension/nemo-emblems.py
This change adds the "-r" option to touch, which reads the timestamps from the file and then applies them to the file.  It's sufficient to generate an inotify event, and the file's mtime doesn't change.
In the event that an OS's touch doesn't support -r, I've added a fallback to the old touch command.
> Don't change the mtime when changing a file's emblems

- nemo-preview/data/style/gtk-style.css
Fixes
```
(nemo-preview-start:23301): Gtk-WARNING **: Theme parsing error: gtk-style.css:12:12: Not using units is deprecated. Assuming 'px'.
(nemo-preview-start:23301): Gtk-WARNING **: Theme parsing error: gtk-style.css:24:26: The :prelight pseudo-class is deprecated. Use :hover instead.
(nemo-preview-start:23301): Gtk-WARNING **: Theme parsing error: gtk-style.css:25:26: The :prelight pseudo-class is deprecated. Use :hover instead.
(nemo-preview-start:23301): Gtk-WARNING **: Theme parsing error: gtk-style.css:29:26: The :prelight pseudo-class is deprecated. Use :hover instead.
(nemo-preview-start:23301): Gtk-WARNING **: Theme parsing error: gtk-style.css:30:26: The :prelight pseudo-class is deprecated. Use :hover instead.
```
> preview: fix some gtk warnings

- nemo-preview/src/js/ui/mainWindow.js
- nemo-preview/src/js/ui/mimeHandler.js
- nemo-preview/src/js/viewers/image.js
Fixes
```
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mimeHandler.js 61]: assignment to undeclared variable idx
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mainWindow.js 33]: assignment to undeclared variable screen
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mainWindow.js 34]: assignment to undeclared variable mon
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mainWindow.js 35]: assignment to undeclared variable s
```
Based on https://git.gnome.org/browse/sushi/patch/src/js/ui/mimeHandler.js?id=a7265a0a451eaddf7a96a41b072bb58d6fa1a579
> Fix assignment to undeclared variables warnings

- nemo-preview/src/js/ui/mainWindow.js
Based on https://git.gnome.org/browse/sushi/commit/?id=9abfea53f833a16a5abca194380814cdd8f96761
```
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mainWindow.js 41]: Requiring GdkX11 but it has 2 versions available; use imports.gi.versions to pick one
```
> mainWindow: specify GdkX11 version to 3.0

- nemo-preview/src/js/ui/mainWindow.js
Based on https://git.gnome.org/browse/sushi/commit/?id=c254e6b54c91f7f8ba54440e8ab437e6a62ad32f
```
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/ui/mainWindow.js 248]: reference to undefined property this._isFullScreen
Cjs-Message: JS WARNING: [resource:///org/cinnamon/cjs/modules/tweener/tweener.js 545]: reference to undefined property properties[istr].arrayIndex
/usr/bin/nemo-preview: line 15:  2885 Segmentation fault      (core dumped) /usr/libexec/nemo-preview-start
```
> mainWindow: fix uninitialized variable

- nemo-preview/src/js/viewers/html.js
Fixes
```
Cjs-Message: JS WARNING: [/usr/share/nemo-preview/js/viewers/html.js 31]: Requiring WebKit2 but it has 2 versions available; use imports.gi.versions to pick one2
```
> specify webkit version to 4.0

- nemo-preview/src/js/viewers/text.js
Based on https://git.gnome.org/browse/sushi/patch/src/js/viewers/text.js?id=f04402a414f038c598c4a9c32f4b95c8e24ec67f
Fixes
```
(nemo-preview-start:10031): Cjs-WARNING **: JS ERROR: Error calling prepare() on viewer: ReferenceError: schema_name is not defined
TextRenderer.prototype.prepare@/usr/share/nemo-preview/js/viewers/text.js:64:52
```
> Fix schema_name not defined and switch to xed

- nemo-preview/debian/control
rpm says it isn't needed and nemo-preview functions without it
> Remove depends gir1.2-clutter-gst-2.0

- nemo-audio-tab/nemo-extension/nemo-audio-tab.glade
- nemo-audio-tab/nemo-extension/nemo-audio-tab.py
Audio tab has seen little love.
This way it start to look at the same level of the other tabs.
> nemo-audio-tab: fixes

- nemo-media-columns/nemo-media-columns.py
I don't know if this is an acceptable fix, but it addresses #176.
It pads out single digit track numbers with a 0 to enable proper sorting inside Nemo.
> nemo-media-columns: Add track padding

- nemo-share/src/install-samba
The way install-samba is currently implemented the command line argument
is prefered to the PKEXEC_UID environment variable. This means if an
admin relaxes the polkit policy to allow non-privileged users to run
this script without admin password, then non-privileged users could add
arbitrary other users to the sambashare group.
This is certainly not the purpose of this helper script. Therefore the
PKEXEC_UID should be preferred and the command line arguments be ignored
if it is present.
> install-samba: prevent unprivileged users to add other users to sambashare

- makepot
- nemo-seahorse/configure.ac
- nemo-seahorse/debian/changelog
- nemo-terminal/src/nemo-terminal-prefs.py
This extension was missed by the makepot script
There's also a gschema.xml file, which has some strings. I didn't
included them, because I don't see, where they are used.
> nemo-terminal: add l10n support

- nemo-dropbox/Makefile.am
- nemo-dropbox/configure.ac
This is explicitly python2 and should use the corresponding versioned path.
> nemo-dropbox: PEP 394 support

- nemo-media-columns/nemo-media-columns.py
```
Traceback (most recent call last):
File "/usr/share/nemo-python/extensions/nemo-media-columns.py", line 119, in update_cb
self.do_update_file_info(file)
File "/usr/share/nemo-python/extensions/nemo-media-columns.py", line 182, in do_update_file_info
except GLib.Error as e:
NameError: name 'GLib' is not defined
```
> Update nemo-media-columns.py: Avoid a NameError

- nemo-media-columns/nemo-media-columns.py
Some files have duration that is a float, causes ValueError: invalid literal for int()
> ensures video duration works when a float

- nemo-media-columns/nemo-media-columns.py
Until now, the pymediainfo library was used on video and non-mp3 mimetypes, but the bitrate field only read for audio tracks.
This resulted in the column only displaying the bitrate of only one (the last) audiotrack, ignoring video and other audio tracks, as well as potentially other tracks.
This patch exchanges displaying the individual track bitrate field `'other_bit_rate'` cumulative bitrate `'other_overall_bit_rate'` if present, i.e. sum of all streams's bitrates as returned by mediainfo.
Support can potentially be further expanded by adding more supported mime types to the list, as the required field seems to always get populated as long as rate calculation (size and runtime) is possible.
> [media-columns] display bitrate for videos

- nemo-preview/src/js/ui/fallbackRenderer.js
```
$ nemo-preview 
Cjs-Message: 15:32:04.773: JS WARNING: [/usr/share/nemo-preview/js/ui/fallbackRenderer.js 29]: Requiring Gtk but it has 3 versions available; use imports.gi.versions to pick one
```
> preview: Fix gtk import

- nemo-preview/src/js/ui/main.js
Similar to change in PR https://github.com/linuxmint/nemo-extensions/pull/415, resolves:
```
Cjs-Message: 00:11:40.228: JS WARNING: [/usr/share/nemo-preview/js/viewers/audio.js 31]: Requiring Gtk but it has 3 versions available; use imports.gi.versions to pick one
...
(nemo-preview-start:403013): Cjs-CRITICAL **: 00:11:40.238: JS ERROR: Error: Unsupported type (null), deriving from fundamental (null)
_init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:38:5
@/usr/share/nemo-preview/js/viewers/audio.js:31:13
/usr/bin/nemo-preview: line 15: 403013 Segmentation fault      (core dumped) /usr/lib/nemo-preview/nemo-preview-start
```
> preview: set gtk 3.0 in ui/main.js for viewers/audio.js

- nemo-preview/src/js/viewers/audio.js
this fixes the error I was getting:
```
Cjs-Message: 14:59:39.333: JS WARNING: [/usr/share/nemo-preview/js/viewers/audio.js 30]: Requiring Gst but it has 2 versions available; use imports.gi.versions to pick one
Cjs-Message: 14:59:39.333: JS WARNING: [/usr/share/nemo-preview/js/viewers/audio.js 31]: Requiring Gtk but it has 3 versions available; use imports.gi.versions to pick one
(nemo-preview-start:23759): GLib-GObject-WARNING **: 14:59:39.341: cannot register existing type 'GtkWidget'
(nemo-preview-start:23759): GLib-GObject-WARNING **: 14:59:39.341: cannot add class private field to invalid type '<invalid>'
(nemo-preview-start:23759): GLib-GObject-WARNING **: 14:59:39.341: cannot add private field to invalid (non-instantiatable) type '<invalid>'
(nemo-preview-start:23759): …
```
> Specify Gst version

- nemo-seahorse/meson.build
- nemo-seahorse/meson_options.txt
meson has the concept of "feature" options. Rather than either enabling or disabling an optional dependency+feature via true/false boolean type, a feature option accepts "enabled", "disabled", and "auto". By passing the feature option directly to the dependency() lookup, meson knows when/how to look it up without if/else soup.
The new functionality here is:
- auto type will try to detect if the dependency is available and use it
- disabled type will log "Dependency avahi-glib skipped: feature sharing disabled"
For equivalence with the previous option values, the default options continue to force enable or force disable the features. No use of "auto" (but people building the project can configure it that way, if they wish).
> simplify meson option handling

- nemo-compare/src/nemo-compare.py
I am using pretty dated arch release package but it seems nemo-compare.py in master branch has the same issue. The fix in this PR allows nemo-compare plugin to run on Nemo 3.0.
> Fixed nemo-compare not working due to PyGIWarning - gi.require_version('Nemo', '3.0')

- nemo-dropbox/README
Noticed that this was still documented as using autotools, this worked on my machine (Debian 11).
> Update to meson build instructions.

- nemo-share/src/shares.c
This little change fixes "net usershare returned error 255" error on some Arch based distributions, when trying to create/modify a share from nemo
- Tested on Manjaro Cinnamon
> Fix "net usershare returned error 255" error

- nemo-image-converter/data/nemo-image-resize.ui
- nemo-image-converter/src/nemo-image-resizer.c
Bug: No size format is set but button "Resize" is activated. Extension displays "no access to the file xy permitted".
Solution: Set a common size format as default in the UI.
> Bugfix nemo-image-converter: missing size format

- nemo-seahorse/meson.build
For a while now:
- upstream gpgme distributes proper pkg-config files
- meson knows how to fall back to gpgme-config if gpgme is too old to have pkg-config files
Use a proper dependency detection method.
Fixes #466
> meson: simplify gpgme dependency lookup

- nemo-python/examples/background-image.py
- nemo-python/examples/block-size-column.py
- nemo-python/examples/md5sum-property-page.py
- nemo-python/examples/open-terminal.py
- nemo-python/examples/update-file-info-async.py
Most changes are simple fixes for the python2 -> python3 transition.
Notable other changes:
- In `md5sum-property-page.py`, the code appears to have been infinitely reading the file, even though it's been fully read. Using `while` fixes that.
- In `open-terminal.py`, opted to call `gnome-terminal` directly without trying to read from GConf, because that seems to fail when using the "Open Terminal In %s" menu item.
Verified that all of the examples work on ALT Linux Sisyphus with:
```
nemo-5.8.2-alt1.x86_64
nemo-python-5.6.0-alt1.x86_64
```
**Edit:** https://github.com/linuxmint/nemo-extensions/pull/486/commits/cb7ef6b11e55668a6c00b0a2b91dfaf26931239e is to prevent an error like below from appearing in terminal when launching `$ nemo` (same as init is done in `update-file-info-async.py`): …
> Fixed `nemo-python` examples

- nemo-compare/src/utils.py
I created hardened linux distribution. /usr/bin and /bin permissions are 111. 
Nemo compare extension require list /usr/bin and It is impossible for distribution.
I fix permission error. If listing is impossible just ignored.
> fix permision error issue

- nemo-audio-tab/nemo-extension/nemo-audio-tab.py
Added Bitrate for FLAC's
Updated Samplerate for FLAC's
> audio-tab: Updated FLAC info

- nemo-image-converter/src/nemo-image-rotator.c
Fixes: #550
Apply the orientation metadata before rotating.
See imagemagick docs: http://www.imagemagick.org/script/command-line-options.php#auto-orient
I have applied the rotate 90° twice to an image with orientation metadata and it worked as expected. (The orientation metadata is stripped after applying it)
> respect orientation metadata when rotating images
