- nemo-share/configure.in
- nemo-share/po/tr.po
fixes https://github.com/linuxmint/nemo-extensions/issues/62
> [nemo-share] added Turkish translation provided by @kelebek333

- nemo-media-columns/nemo-media-columns.py
This Patch adds a column for exif xmp rating.
This makes it easy to sort pictures by rating.
> Exif XMP Rating Column

- nemo-audio-tab/debian/changelog
- nemo-audio-tab/debian/copyright
- nemo-audio-tab/debian/install
- nemo-audio-tab/nemo-extension/nemo-audio-tab.py
- nemo-audio-tab/setup.py
This will now build properly, whoops :P
> Fix debian and setup left over from last commit

- nemo-preview/src/libnemo-preview/nemo-preview-font-loader.c
https://git.gnome.org/browse/sushi/commit/?id=9f068361a4f0e2ef0b48cdac763e16941e758ed1
> FontLoader: don't use deprecated methods

- nemo-terminal/src/nemo_terminal.py
> nemo-terminal: fix for F4 being too responsive

- nemo-terminal/src/nemo_terminal.py
> Save current visibility.

- nemo-rabbitvcs/RabbitVCS.py
Fixes https://github.com/linuxmint/nemo-extensions/issues/168
> Rabbitvcs: Specify nemo import version

- nemo-preview/src/js/viewers/image.js
Based on https://git.gnome.org/browse/sushi/patch/src/js/viewers/image.js?id=4190a0070445a44e5bb1a6c8b238d263c94308b6
> image: add support for GIF animations

- nemo-preview/data/style/gtk-style.css
see https://mail.gnome.org/archives/commits-list/2014-May/msg03022.html
> Preview: fix gtk warning

- nemo-python/src/nemo-python.c
Based on https://git.gnome.org/browse/nautilus-python/commit/?id=8c88de8da429cff12d10f7822a063c4f56d8bbe7
> redo Added gi.require_version()

- nemo-emblems/nemo-extension/nemo-emblems.py
fixes https://github.com/linuxmint/nemo-extensions/issues/299
> fix nemo-emblems not working

- nemo-emblems/nemo-extension/nemo-emblems.py
- nemo-seahorse/configure.ac
- nemo-seahorse/debian/changelog
binding gettext domain needs to be done later, else it doesn't get
translated
> emblems: l10n fix

- nemo-share/interfaces/share-dialog.ui
- nemo-share/src/Makefile.am
- nemo-share/src/check-directory-permissions
- nemo-share/src/install-samba
- nemo-share/src/nemo-share.c
- nemo-share/src/org.nemo.share.samba_install.policy.in
This PR addresses some of the samba related issues described in https://github.com/linuxmint/linuxmint/issues/125.
> Samba improvements

- nemo-preview/src/js/viewers/text.js
Fixes https://github.com/linuxmint/xreader/issues/310
> Add import version for  GtkSource

- nemo-dropbox/README
Hello,
I just struggled with installing nemo-dropbox for a bit and I thought that a small addition to the README would have made it a little easier for me.
Best regards
> nemo-dropbox: Minor README change

- nemo-python/meson.build
See https://bugs.python.org/issue36721
Fixes #336
> nemo-python: be compatible with python 3.8

- nemo-python/src/nemo-python-object.c
- nemo-python/src/nemo-python.c
- nemo-python/src/nemo-python.h
Fixes #351 FTBFS with gcc-10 'multiple definition of'
> Fix issue #351

- nemo-media-columns/nemo-media-columns.py
works only with two "f"s in tiff
> support for tiff images

- nemo-media-columns/nemo-media-columns.py
just added extra column to columns generated by nemo-media-columns, the column shows the pages count of a PDF file, i think it might be useful for others.
so will you give me the honor if this tiny contribution? :D xD
> add PDF pages count column to nemo-media-columns

- nemo-fileroller/src/nemo-fileroller.c
> [nemo-fileroller] Support for Zstandard archives

- nemo-media-columns/setup.py
> [media-columns] add missing dependency to comment

- nemo-terminal/src/nemo_terminal.py
- nemo-terminal/src/org.nemo.extensions.nemo-terminal.gschema.xml
> Do not execute pending command when directory changes

- nemo-media-columns/nemo-media-columns.py
Fixes #428 
I have checked this on my machine and it works fine.
> Add M4A support. Add composer, description field support to m4a & mp3

- nemo-preview/debian/control
- nemo-preview/meson.build
- nemo-preview/src/js/viewers/html.js
> Switch to webkit2gtk-4.1

- nemo-dropbox/meson.build
- nemo-fileroller/meson.build
- nemo-image-converter/meson.build
- nemo-python/meson.build
- nemo-python/src/meson.build
- nemo-repairer/meson.build
- nemo-seahorse/meson.build
- nemo-share/meson.build
Similar to linuxmint/cinnamon#11870
Similar to linuxmint/cinnamon-control-center#318
Similar to linuxmint/cinnamon-desktop#234
Similar to linuxmint/cinnamon-menus#67
Similar to linuxmint/cinnamon-screensaver#444
Similar to linuxmint/cinnamon-session#155
Similar to linuxmint/cinnamon-settings-daemon#383
Similar to linuxmint/cjs#119
Similar to linuxmint/muffin#675
Similar to linuxmint/nemo#3316
Similar to linuxmint/xapp#172
> Fix meson.build deprecations up to 0.56.0

- nemo-preview/src/libnemo-preview/nemo-preview-cover-art.c
based on https://github.com/GNOME/sushi/commit/a5dec7e53915631cc3c182fe330ef3e0391fdbd4
> cover-art: fix compilation error

- nemo-audio-tab/nemo-extension/nemo-audio-tab.py
- nemo-compare/src/nemo-compare.py
- nemo-emblems/nemo-extension/nemo-emblems.py
- nemo-media-columns/nemo-media-columns.py
- nemo-pastebin/src/nemo-pastebin.py
- nemo-terminal/src/nemo_terminal.py
> Fix python NameError: '_' is not defined
